gemini.api.key=${GEMINI-API-KEY}
gemini.model=gemini-2.5-flash

server.error.include-message=always
server.error.include-binding-errors=always
spring.mvc.problemdetails.enabled=false
spring.output.ansi.enabled=always